In [1]:
import pandas as pd
import pymysql
from sqlalchemy import create_engine

In [11]:
engine = create_engine('mysql+pymysql://root:Pallyo_40@localhost/sakila')

In [18]:
query = '''
select i.film_id, avg(p.amount) avg_rental_cost,
case when timestampdiff(hour, r.rental_date, r.return_date) regexp '^[0-9]+$'
then avg(timestampdiff(hour, r.rental_date, r.return_date))
else 0
end as avg_hous_rented, count(ifnull(r.rental_id, 0)) num_rent
from rental r
join payment p on p.rental_i = r.rental_id
join inventory i on i.inventory_id = r.inventory_id
group by film_id;'''

In [19]:
new_table = pd.read_sql_query(query, engine)

OperationalError: (pymysql.err.OperationalError) (1054, "Unknown column 'p.rental_i' in 'on clause'")
[SQL:
select i.film_id, avg(p.amount) avg_rental_cost,
case when timestampdiff(hour, r.rental_date, r.return_date) regexp '^[0-9]+$'
then avg(timestampdiff(hour, r.rental_date, r.return_date))
else 0
end as avg_hous_rented, count(ifnull(r.rental_id, 0)) num_rent
from rental r
join payment p on p.rental_i = r.rental_id
join inventory i on i.inventory_id = r.inventory_id
group by film_id;]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

In [15]:
new_table

     film_id  avg_rental_cost  avg_hours_rented  num_rent
0          1         1.598696          119.4545        23
1          2         7.561429          135.1667         7
2          3         3.156667           82.7500        12
3          4         3.990000          113.6364        23
4          5         4.323333          170.0000        12
..       ...              ...               ...       ...
953      996         0.990000          110.2857         7
954      997         2.823333          133.1667         6
955      998         1.656667          142.3750         9
956      999         4.342941          132.5294        17
957     1000         6.925484          108.5161        31

[958 rows x 4 columns]

In [6]:
query = '''
select i.film_id, avg(p.amount) avg_rental_cost,
case when timestampdiff(hour, r.rental_date, r.return_date) regexp '^[0-9]+$'
then avg(timestampdiff(hour, r.rental_date, r.return_date))
else 0
end as avg_hours_rented, count(ifnull(r.rental_id, 0)) num_rent
from rental r
join payment p on p.rental_id = r.rental_id
join inventory i on i.inventory_id = r.inventory_id
group by film_id;

select
  f.film_id,
  f.title,
  f.description,
  fc.category_id,
  f.language_id,
  avg(f.rental_duration) * 24 avg_hours_rental_allowed,
  f.length / 60 hours_length,
  avg(f.replacement_cost) avg_replacement_cost,
  f.rating,
  f.special_features,
  count(fa.actor_id) actors_in_film
from film f
join film_category fc on fc.film_id = f.film_id
join film_actor fa on fa.film_id = f.film_id
group by f.film_id;

select
  act2.film_id,
  group_concat(act2.actor_id separator ',') actor_list,
  sum(act2.actor_fame) total_actor_fame,
  sum(act2.actor_influence) total_actor_influence
from (
  select fa.film_id, act1.*
    from (
      select
        fa1.actor_id,
        count(distinct(fa1.film_id)) actor_fame,
        count(distinct(fa2.actor_id)) actor_influence
        from
          film_actor fa1
          join film_actor fa2 on fa2.film_id = fa1.film_id
          group by fa1.actor_id
    ) act1
    join film_actor fa on fa.actor_id = act1.actor_id
) act2
group by act2.film_id;'''

In [7]:
data = pd.read_sql(query, engine)

ProgrammingError: (pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select\n  f.film_id,\n  f.title,\n  f.description,\n  fc.category_id,\n  f.language_i' at line 11")
[SQL:
select i.film_id, avg(p.amount) avg_rental_cost,
case when timestampdiff(hour, r.rental_date, r.return_date) regexp '^[0-9]+$'
then avg(timestampdiff(hour, r.rental_date, r.return_date))
else 0
end as avg_hours_rented, count(ifnull(r.rental_id, 0)) num_rent
from rental r
join payment p on p.rental_id = r.rental_id
join inventory i on i.inventory_id = r.inventory_id
group by film_id;

select
  f.film_id,
  f.title,
  f.description,
  fc.category_id,
  f.language_id,
  avg(f.rental_duration) * 24 avg_hours_rental_allowed,
  f.length / 60 hours_length,
  avg(f.replacement_cost) avg_replacement_cost,
  f.rating,
  f.special_features,
  count(fa.actor_id) actors_in_film
from film f
join film_category fc on fc.film_id = f.film_id
join film_actor fa on fa.film_id = f.film_id
group by f.film_id;

select
  act2.film_id,
  group_concat(act2.actor_id separator ',') actor_list,
  sum(act2.actor_fame) total_actor_fame,
  sum(act2.actor_influence) total_actor_influence
from (
  select fa.film_id, act1.*
    from (
      select
        fa1.actor_id,
        count(distinct(fa1.film_id)) actor_fame,
        count(distinct(fa2.actor_id)) actor_influence
        from
          film_actor fa1
          join film_actor fa2 on fa2.film_id = fa1.film_id
          group by fa1.actor_id
    ) act1
    join film_actor fa on fa.actor_id = act1.actor_id
) act2
group by act2.film_id;]
(Background on this error at: http://sqlalche.me/e/13/f405)